name: Reusable workflow
 
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
 
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.time }}
      current-person:
        description: 'The person.'
        value: ${{ jobs.reusable-job.outputs.person }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      time: ${{ steps.time.outputs.time }}
      person: ${{ steps.person.outputs.person }}
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
 
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT

      - name: Person
        id: person
        run: echo "person=krzysztof" >> $GITHUB_OUTPUT
